# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.7
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      # - run:
      #     name: "Installing dependencies"
      #     command: |
      #       python3 -m venv venv
      #       . venv/bin/activate 
      #       pip3.9 install -r requirements-dev.txt
      # - restore_cache:
      #     keys:
      #       - processing-{{ arch }}-v2-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      #       - processing-{{ arch }}-v2-
      - run:
          name: Running tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 manage.py test
            $HOME/.local/bin/coverage run --source "journal_app" manage.py test -v 2 && coverage report
            $HOME/.local/bin/coverage html  # open htmlcov/index.html in a browser
      - save_cache:
          key: processing-{{ arch }}-v2-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - venv

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
